---
- name: Ensure Visual Studio Code is installed
  command: snap install code --classic

- name: Install VirtualBox
  apt:
    name: ['virtualbox', 'virtualbox-qt', 'virtualbox-dkms', 'virtualbox-guest-additions-iso']
    state: present

- name: Install Vagrant
  apt:
    name: vagrant
    state: present

- name: Install packer
  apt:
   name: packer
   state: present

- name: Install GitKraken
  command: snap install gitkraken

- name: Clone VimWiki Repository
  git:
    repo: https://github.com/vimwiki/vimwiki.git
    dest: ~/.vim/pack/plugins/start/vimwiki

- name: Install net-tools
  apt:
    name: net-tools
    state: present

- name: Ensure qemu/virt-manager is installed
  apt:
    name: ['qemu-kvm', 'virt-manager']
    state: present

- name: Ensure remmina is installed
  apt:
    name: remmina
    state: present
