---
- name: Ensure Visual Studio Code is installed
  command: snap install code --classic

- name: Install VirtualBox
  apt:
    name: virtualbox
    state: present

- name: Install Vagrant
  apt:
    name: vagrant
    state: present

- name: Install packer
  apt:
   name: packer
   state: present

- name: Install GitKraken
  command: snap install gitkraken
