---
- name: Ensure Visual Studio Code is installed
  snap:
    name: code
    classic: yes
    state: present
  become: yes

- name: Ensure VirtualBox is installed
  apt:
    name: ['virtualbox', 'virtualbox-qt', 'virtualbox-dkms', 'virtualbox-guest-additions-iso']
    state: present
  become: yes

- name: Ensure Vagrant is installed
  apt:
    name: vagrant
    state: present
  become: yes

- name: Ensure packer is installed
  apt:
   name: packer
   state: present
  become: yes

- name: Ensure GitKraken is installed
  snap:
    name: gitkraken
    classic: yes
    state: present
  become: yes

- name: Clone VimWiki Repository
  git:
    repo: https://github.com/vimwiki/vimwiki.git
    dest: ~/.vim/pack/plugins/start/vimwiki

# - name: Install net-tools
#   apt:
#     name: net-tools
#     state: present
#   become: yes

- name: Ensure qemu/virt-manager is installed
  apt:
    name: ['qemu-kvm', 'virt-manager']
    state: present
  become: yes

- name: Ensure Remmina is installed
  apt:
    name: remmina
    state: present
  become: yes
