---
- name: Install Chromium
  apt:
    name: chromium-browser
    state: present

- name: Install GIMP
  apt:
    name: gimp
    state: present

- name: Install Hiri
  command: snap install hiri

- name: Install Spotify
  command: snap install spotify

- name: Install Dash to Dock
  apt:
    name: gnome-shell-extension-dashtodock
    state: present

- name: Install Atom
  command: snap install atom --classic
  
- name: Install LibreOffice
  apt:
    name: libreoffice
    state: present

- name: Install Mailspring
  command: snap install mailspring

- name: Install Nextcloud
  command: snap install nextcloud-client

- name: Install VirtualBox
  apt:
    name: virtualbox
    state: present

- name: Install Vagrant
  apt:
    name: vagrant
    state: present

- name: Install GitKraken
  command: snap install gitkraken

- name: Install gnome tweak tool
  apt:
    name: gnome-tweak-tool
    state: present

- name: Install KeePassXC
  apt:
    name: keepassxc
    state: present

- name: Install Dolphin
  apt:
    name: dolphin
    state: present

- name: Install kio-extras (smb)
  apt:
    name: kio-extras
    state: present

- name: Install gnupg2
  apt:
    name: gnupg2
    state: present

- name: Install guake
  apt:
    name: guake
    state: present