---
- name: Install LibreOffice
  apt:
    name: libreoffice
    state: present
  become: yes

    # - name: Install kio-extras (smb)
    #   apt:
    #     name: kio-extras
    #     state: present

- name: Install Mailspring
  command: snap install mailspring
  become: yes

- name: Install Chromium
  apt:
    name: chromium-browser
    state: present
  become: yes
