---
- name: Install GIMP
  apt:
    name: gimp
    state: present
  become: yes

- name: Install Spotify
  snap:
    name: spotify
    state: present
  become: yes

- name: Add Nextcloud Repository
  apt_repository:
    repo: ppa:nextcloud-devs/client
    state: present
    update_cache: yes
  become: yes

- name: Install Nextcloud
  apt:
    name: nextcloud-client
    state: present
  become: yes

- name: Install KeePassXC
  apt:
    name: keepassxc
    state: present
  become: yes

