---
- name: Ensure GIMP is installed
  apt:
    name: gimp
    state: present
  become: yes

- name: Ensure Spotify is installed
  snap:
    name: spotify
    state: present
  become: yes

- name: Add Nextcloud Repository
  apt_repository:
    repo: ppa:nextcloud-devs/client
    state: present
    update_cache: yes
  become: yes

- name: Ensure Nextcloud client is installed
  apt:
    name: nextcloud-client
    state: present
  become: yes

- name: Ensure KeePassXC is installed
  apt:
    name: keepassxc
    state: present
  become: yes

