---
# - name: Install gnupg2
#   apt:
#     name: gnupg2
#     state: present

- name: Ensure gnome tweak tool is installed
  apt:
    name: gnome-tweak-tool
    state: present
  become: yes

- name: Ensure cifs-utils is installed (smb)
  apt:
    name: cifs-utils
    state: present
  become: yes
